name: Build

on:
    workflow_call:
      inputs:
        workspace:
          required: true
          type: string
        trigger:
          required: true
          type: string
  
jobs:
    build:
        name: Terraform Validate, Lint & Plan
        if: ${{ inputs.trigger }} != "deleted"
        runs-on: ubuntu-latest
        env:
          TF_WORKSPACE: Team-${{ inputs.workspace }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - uses: hashicorp/setup-terraform@v2
              with:
                cli_config_credentials_token: ${{ secrets.TF_TOKEN }}
                terraform_version: 1.5.0
      
            - name: Terraform Init
              id: init
              run: terraform init -upgrade
      
            - name: Terraform Validate
              id: validate
              run: terraform validate -no-color
      
            - name: Setup TFLint
              uses: terraform-linters/setup-tflint@v4
              with:
                tflint_version: v0.42.2
      
            - name: Terraform Lint
              id: lint
              run: tflint --var-file=Team-${{ inputs.workspace }}.tfvars
      
            - name: Terraform Plan
              id: plan
              run: terraform plan -var-file=Team-${{ inputs.workspace }}.tfvars -no-color -input=false -lock=false -out=Team-${{ inputs.workspace }}.tfplan

            - uses: actions/upload-artifact@v3
              with:
                name: Team-${{ inputs.workspace }}.tfplan
                path: Team-${{ inputs.workspace }}.tfplan